# Use an official nginx image as the base image
FROM nginx:alpine

# Set the working directory
WORKDIR /usr/share/nginx/html

# Copy the contents of your project into the container
COPY . .

# Expose port 80 to access the app on localhost
EXPOSE 80
